### PR TITLE
Turn kemonomimichan into shiggy

### PR DESCRIPTION
**Pull request by byeoon**
title, kind of a shitpost pull request but maybe could turn it into a setting on which one you want to show (or make it a random chance)

image

### CODE REVIEW

**Comment by acquitelol** [comment]
you know kemonomimi chan is the official name for shiggy right, like in the mangas and stuff

**Comment by byeoon** [comment]
> you know kemonomimi chan is the official name for shiggy right, like in the mangas and stuff

yea i know, but shiggy is silly
Also wait holy shit there's a manga???

**Comment by byeoon** [comment]
It's apparently Kemomimichan instead of Kemonomimichan just a heads up

**Comment by acquitelol** [comment]
meow

**Pull request closed without merging**
